= SeaLion Mission Concept of Operations (ConOps)
:revnumber: v0.4.0
:toc: left

ifndef::backend-pdf[]
image:https://img.shields.io/badge/License-MIT-yellow.svg[MIT License, link=https://opensource.org/licenses/MIT]
image:https://img.shields.io/badge/Contribute%20on-GitHub-orange[Contribute on GitHub, link=https://github.com/ODU-CGA-CubeSat/mission-conops.git]
image:https://img.shields.io/badge/Download%20-PDF-blue[Download PDF, link=https://ODU-CGA-CubeSat.github.io/mission-conops/mission-conops.pdf]
endif::[]

<<<

== Stakeholder Needs
 
The SeaLion Mission Concept of Operations (ConOps) is guided by a series of stakeholder needs, listed below.


.Stakeholder Need 1.1: Primary Mission Objective A1
****
The SeaLion mission shall establish UHF communication link with Virginia ground station
**** 

.Stakeholder Need 1.2: Primary Mission Objective A2
****
The SeaLion mission shall establish S-Band communication link with MC3 ground station
**** 

.Stakeholder Need 1.3: Primary Mission Objective A3
****
The SeaLion mission shall successfully transmit “mission data” defined above to ground stations on the Earth.
**** 

.Stakeholder Need 1.4: Primary Mission Objective A4
****
The SeaLion mission shall adhere to CubeSat standards as per CDS Rev. 13
**** 

.Stakeholder Need 2.1: Secondary Mission Objective B1
****
The SeaLion mission shall provide a means to validate an impedance probe in-orbit
**** 

.Stakeholder Need 2.2: Secondary Mission Objective B2
****
The SeaLion mission shall provide a means to validate a V-Infrared Sensor (VIR-S) in-orbit
**** 

.Stakeholder Need 2.3: Secondary Mission Objective B3
****
The SeaLion mission shall provide a means to validate a deployable composite structure (DeCS) in-orbit
**** 

.Stakeholder Need 3.1: Tertiary Mission Objective C1
****
The SeaLion mission shall qualify a newly developed antenna
**** 

.Stakeholder Need 3.2: Tertiary Mission Objective C2
****
The SeaLion mission shall qualify a CubeSat bus architecture for very-low Earth orbit (VLEO)
**** 

.Stakeholder Need 3.3: Tertiary Mission Objective C3
****
The SeaLion shall verify DeCS in-orbit behavior performance via accelerometer & temperature sensor data
**** 


== User Stories

The SeaLion Mission Concept of Operations (ConOps)'s stakeholder needs are then used to identify a series of user stories which then lead to design decisions captured in data structure and activity definitions.


=== User Story 1: Ping Satellite

****
As a *Ground Station Operator* I want to *Ping satellite* so that I can *Establish communication link with satellite*.
****

==== Example:

Ping the satellite in order to establish UHF communication link with Virginia ground station


==== *Derived From:*




* Primary Mission Objective A1





=== User Story 2: View Satellite Health Data Packet

****
As a *Ground Station Operator* I want to *View satellite health data packet* so that I can *Validate that satellite is operating nominally*.
****

==== Example:

View satellite satellite health data packet in order to validate the mission data of the IP and DeCS payloads


==== *Derived From:*




* Primary Mission Objective A2




* Primary Mission Objective A3




* Tertiary Mission Objective C3





=== User Story 2.1: Query Satellite Health Data Packet

****
As a *Ground Station Operator* I want to *Send satellite health data packet downlink command* so that I can *Request satellite health data packet*.
****

==== Example:

Send satellite health data packet downlink command in order to aquire satellite health data packet downlink


==== *Derived From:*








=== User Story 2.2: Listen for Satellite Beacon

****
As a *Ground Station Operator* I want to *Open ground station beacon monitor* so that I can *View satellite health data packet*.
****

==== Example:

Open ground station beacon monitor to listen for satellite health data packet downlink


==== *Derived From:*









