= Flight Software Systems Architecture for the Sealion Mission
:presentation_title: Flight Software Systems Architecture for the Sealion Mission

v3.0.1

by Robert Borowicz, Patrick Clark, Kevin Chiu, Gonzalo Fernandez Mediavilla, Bhagatji Jimesh, Sean Marquez, Payal Nandi, Joseph Siciliano, & Gus Williams

== Homepage

https://ODU-CGA-CubeSat.github.io/sealion-mission-architecture

== Design Philosophy

The {presentation_title} follows a https://www.writethedocs.org/guide/docs-as-code/[docs-as-code] & https://www.writethedocs.org/videos/portland/2019/lessons-learned-in-a-year-of-docs-driven-development-jessica-parsons/[docs-driven development] approach, as to ensure:

* Documentation and development are tightly coupled.
* No requirement or feature goes undocumented.

== Stakeholder Needs
 
The {presentation_title} is guided by a series of stakeholder needs...


=== 1.1: Primary Mission Objective A1
****
The SeaLion mission shall establish UHF communication link with Virginia ground station
**** 




=== 1.2: Primary Mission Objective A2
****
The SeaLion mission shall establish S-Band communication link with MC3 ground station
**** 




=== 1.3: Primary Mission Objective A3
****
The SeaLion mission shall successfully transmit “mission data” defined above to ground stations on the Earth.
**** 




=== 1.4: Primary Mission Objective A4
****
The SeaLion mission shall adhere to CubeSat standards as per CDS Rev. 13
**** 


==== *Reference:*



* https://www.cubesat.org/s/cds_rev13_final2.pdf[CubeSat Design Specification Rev. 13]





=== 1.5: Primary Mission Objective A5
****
The SeaLion mission shall validate the operation of the Impedance Probe (IP) as a primary payload in-orbit.
**** 




=== 2.1: Secondary Mission Objective B1
****
The SeaLion mission shall provide a means to validate a Multi-spectral Sensor (Ms-S) in-orbit
**** 




=== 2.2: Secondary Mission Objective B2
****
The SeaLion mission shall provide a means to validate a deployable composite structure (DeCS) in-orbit
**** 




=== 3.1: Tertiary Mission Objective C1
****
The SeaLion mission shall qualify on-orbit the deployment and functioning of the newly developed UHF antenna system and its deployment.
**** 




=== 3.2: Tertiary Mission Objective C2
****
The SeaLion mission shall qualify a CubeSat bus architecture for very-low Earth orbit (VLEO)
**** 




=== 3.3: Tertiary Mission Objective C3
****
The SeaLion shall verify DeCS in-orbit behavior performance.
**** 





== User Stories

The {presentation_title}'s stakeholder needs are then used to identify a series of user stories which then lead to design decisions captured in data structure and activity definitions.


=== 1: Ping Satellite

****
As a *Ground Station Operator* I want to *Ping satellite* so that I can *Establish communication link with satellite*.
****

==== Example:

Ping the satellite in order to establish UHF communication link with Virginia ground station


==== *Derived From:*




* xref:{doc-name}#_1_1_primary_mission_objective_a1[Primary Mission Objective A1]





=== 2: View Satellite Health Data Packet

****
As a *Ground Station Operator* I want to *view satellite health data packet* so that I can *validate that satellite is operating nominally*.
****

==== Example:

View satellite health data packet to verify or validate AODS sensor & GPS data is within nominal range and/or corresponds to expected orbit profile




=== 2.1: Listen for Satellite Beacon

****
As a *Ground Station Operator* I want to *Open ground station beacon monitor* so that I can *View satellite health data packet*.
****

==== Example:

Open ground station beacon monitor to listen for satellite health data packet downlink


==== *Derived From:*




* xref:{doc-name}#_2_view_satellite_health_data_packet[View Satellite Health Data Packet]





=== 3: Update Beacon Rate

****
As a *Ground Station Operator* I want to *Update Beacon Rate* so that I can *Conserve power budget*.
****

==== Example:

Update beacon rate to transmit every 30 minutes to conserve power




=== 4: Request Telemetry Data

****
As a *Ground Station Operator* I want to *Request satellite telemetry data packets* so that I can *Locally verify/validate onboard AODS computations*.
****

==== Example:

Request satellite telemetry packets for local verification/validation of onboard AODS computations




=== 4.1: Request Satellite Health Data

****
As a *Ground Station Operator* I want to *request satellite health data packet* so that I can *verify/validate AODS sensors & GPS data are within nominal parameters*.
****

==== Example:

Request satellite health data packet to verify or validate AODS sensors and GPS data correspond to expected attitude and/or orbit profile based on pre-computed attitude or orbit propagation model


==== *Derived From:*




* xref:{doc-name}#_4_request_telemetry_data[Request Telemetry Data]





=== 4.2: Request Satellite AODS Sensor Data

****
As a *Ground Station Operator* I want to *request satellite AODS sensor data* so that I can *verify AODS sensor data yields nominal parameters*.
****

==== Example:

Request satellite AODS sensor data for verifying AODS sensor data corresponds with a known magnetic field, light source, and/or change in orientation w.r.t. satellites body frame of reference


==== *Derived From:*




* xref:{doc-name}#_4_request_telemetry_data[Request Telemetry Data]





=== 5: Payload Scheduler

****
As a *Ground Station Operator* I want to *schedule data collection to occur at specfied orbital position* so that I can *allow satellite mission modes to autonomously record data*.
****

==== Example:






=== 5.1: Deployable Composite Structure (DeCS) Payload Scheduler

****
As a *Ground Station Operator* I want to *schedule data collection to occur at specfied orbital position* so that I can *allow satellite mission modes to autonomously record data*.
****

==== Example:

Schedule data recording at specfic orbital location to another orbital location for Deployable Composite Structure Payload


==== *Derived From:*




* xref:{doc-name}#_2_2_secondary_mission_objective_b2[Secondary Mission Objective B2]




* xref:{doc-name}#_3_3_tertiary_mission_objective_c3[Tertiary Mission Objective C3]





=== 5.2: Impedance Probe Payload Scheduler

****
As a *Ground Station Operator* I want to *Schedule data recording at specfic orbital location* so that I can *Recording data for future transmission*.
****

==== Example:

Schedule data recording at specfic orbital location to another orbital location for impedance probe payload


==== *Derived From:*




* xref:{doc-name}#_1_5_primary_mission_objective_a5[Primary Mission Objective A5]





=== 5.3: Multi-spectral Sensor Scheduler

****
As a *Ground Station Operator* I want to *Schedule data recording at specfic orbital location* so that I can *Recording data for future transmission*.
****

==== Example:

Schedule data recording at specfic orbital location to another orbital location for Multi-spectral Sensor payload


==== *Derived From:*




* xref:{doc-name}#_2_1_secondary_mission_objective_b1[Secondary Mission Objective B1]





=== 5.4: Downlink Payload Data TLE

****
As a *Ground Station Operator* I want to *Transmit TLE schedulered satellite recorded data to ground station* so that I can *Vacant on-board memory for more data*.
****

==== Example:

Start downlink TLE schedulered payload data once the satellite is in line of sight


==== *Derived From:*




* xref:{doc-name}#_1_3_primary_mission_objective_a3[Primary Mission Objective A3]





=== 6: Payload Scheduler

****
As a *Ground Station Operator* I want to *Schedule data recording at specfic time interval* so that I can *Recording data for future transmission*.
****

==== Example:






=== 6.1: Deployable Composite Structure (DeCS) Payload Scheduler

****
As a *Ground Station Operator* I want to *Schedule data recording at specfic time interval (or orbital location)* so that I can *Recording data for future transmission*.
****

==== Example:

Schedule data recording at specfic time interval  for Deployable Composite Structure Payload


==== *Derived From:*




* xref:{doc-name}#_2_2_secondary_mission_objective_b2[Secondary Mission Objective B2]




* xref:{doc-name}#_3_3_tertiary_mission_objective_c3[Tertiary Mission Objective C3]





=== 6.2: Impedance Probe Payload Scheduler

****
As a *Ground Station Operator* I want to *Schedule data recording at specfic time interval* so that I can *Recording data for future transmission*.
****

==== Example:

Schedule data recording at specfic time interval for Impedance Probe Payload


==== *Derived From:*




* xref:{doc-name}#_1_5_primary_mission_objective_a5[Primary Mission Objective A5]





=== 6.3: Multi-spectral Sensor Payload Scheduler

****
As a *Ground Station Operator* I want to *Schedule data recording at specfic time interval* so that I can *Recording data for future transmission*.
****

==== Example:

Schedule data recording at specfic time interval for Multi-spectral Sensor Payload


==== *Derived From:*




* xref:{doc-name}#_2_1_secondary_mission_objective_b1[Secondary Mission Objective B1]





=== 6.4: Downlink Payload Data Time Interval

****
As a *Ground Station Operator* I want to *Transmit time interval schedulered satellite recorded data to ground station* so that I can *Vacant on-board memory for more data*.
****

==== Example:

Start downlink time interval schedulered payload Data once the satellite is in line of sight


==== *Derived From:*




* xref:{doc-name}#_1_3_primary_mission_objective_a3[Primary Mission Objective A3]






=== User stories as Use Case Diagram

[plantuml, use-case-diagram, svg]
....
include::./use-case-diagram.puml[User Stories as Use Case Diagram]
....

== Data Structures
This section covers each data structure type in the *{presentation_title}*.


=== Satellite Health Data Packet
*Purpose:* Data structure for satellite health data packet used for beacon telemetry

=== Satellite Health Data Packet Template
----
call_sign: {{call_sign}}
battery_health: {{battery_health}}
mode: {{mode}}
tle_data: {{tle_data}}

----

=== Satellite Health Data Packet Specification
|===
|Field |Type |Item Type |Description |Source


|call_sign
|string

|

|Identifying call sign for the Sealion mission.

|



|battery_health
|float

|

|Percent value indicating the remaining charge of the batteries.

|



|mode
|integer

|

|Integer value indicating current mission mode. 0 = Safe, 1 = mission mode 1, 2 = mission mode 2, 3 = mission mode 3.

|



|tle_data
|3-DataStructures/4-TLE.yaml

|

|TLE data from orbit propogator at time of beacon.

|



|===


==== *Derived From:*




* xref:{doc-name}#_2_view_satellite_health_data_packet[View Satellite Health Data Packet]




* xref:{doc-name}#_4_1_request_satellite_health_data[Request Satellite Health Data]





=== Satellite AODS IC Data
*Purpose:* Data structure for satellite AODS initial conditions data packet used for attitude determination and orbit propagation

=== Satellite AODS IC Data Template
----
imu_gyro_x: {{imu_gyro_x}}
imu_gyro_y: {{imu_gyro_y}}
imu_gyro_z: {{imu_gyro_z}}
imu_magnetometer_x: {{imu_magnetometer_x}}
imu_magnetometer_y: {{imu_magnetometer_y}}
imu_magnetometer_z: {{imu_magnetometer_z}}
sun_sensor_pitch_pos: {{sun_sensor_pitch_pos}}
sun_sensor_pitch_neg: {{sun_sensor_pitch_neg}}
sun_sensor_yaw_pos: {{sun_sensor_yaw_pos}}
sun_sensor_yaw_neg: {{sun_sensor_yaw_neg}}
sun_sensor_roll_pos: {{sun_sensor_roll_pos}}
sun_sensor_roll_neg: {{sun_sensor_roll_neg}}
time_stamp: {{time_stamp}}
altitude_data_GPS: {{altitude_data}}
lattitude_GPS: {{lattitude}}
longitude_GPS: {{longitude}}

----

=== Satellite AODS IC Data Specification
|===
|Field |Type |Item Type |Description |Source


|imu_gyro_x
|float

|

|The angular rate of the body with to respective to the x-axis in the IMU's reference frame.

|



|imu_gyro_y
|float

|

|The angular rate of the body with to respective to the y-axis in the IMU's reference frame.

|



|imu_gyro_z
|float

|

|The angular rate of the body with to respective to the z-axis in the IMU's reference frame.

|



|imu_magnetometer_x
|float

|

|The magnetic field strength with respective to the x-axis in the IMU's reference frame.

|



|imu_magnetometer_y
|float

|

|The magnetic field strength with respective to the y-axis in the IMU's reference frame.

|



|imu_magnetometer_z
|float

|

|The magnetic field strength with respective to the z-axis in the IMU's reference frame.

|



|sun_sensor_pitch_pos
|float

|

|Sun sensor measurement with respect to positive pitch angle.

a|
* []




|sun_sensor_pitch_neg
|float

|

|Sun sensor measurement with respect to negative pitch angle.

a|
* []




|sun_sensor_yaw_pos
|float

|

|Sun sensor measurement with respect to positive yaw angle.

a|
* []




|sun_sensor_yaw_neg
|float

|

|Sun sensor measurement with respect to negative yaw angle.

a|
* []




|sun_sensor_roll_pos
|float

|

|Sun sensor measurement with respect to positive roll angle.

a|
* []




|sun_sensor_roll_neg
|float

|

|Sun sensor measurement with respect to negative roll angle.

a|
* []




|time_stamp
|string

|

|Time stamp of the last transmission.

|



|altitude_data_GPS
|float

|

|The altitude data of the satellite from GPS.

|



|lattitude_GPS
|float

|

|Lattitude coordinate of the satellite from GPS.

|



|longitude_GPS
|float

|

|Longitude coordinate of the satellite from GPS.

|



|===


==== *Derived From:*








=== Satellite AODS Sensor Data
*Purpose:* Data structure for satellite AODS sensor data used for attitude determination or incremental orbit propogation

=== Satellite AODS Sensor Data Template
----
imu_gyro_x: {{imu_gyro_x}}
imu_gyro_y: {{imu_gyro_y}}
imu_gyro_z: {{imu_gyro_z}}
imu_magnetometer_x: {{imu_magnetometer_x}}
imu_magnetometer_y: {{imu_magnetometer_y}}
imu_magnetometer_z: {{imu_magnetometer_z}}
sun_sensor_pitch_pos: {{sun_sensor_pitch_pos}}
sun_sensor_pitch_neg: {{sun_sensor_pitch_neg}}
sun_sensor_yaw_pos: {{sun_sensor_yaw_pos}}
sun_sensor_yaw_neg: {{sun_sensor_yaw_neg}}
sun_sensor_roll_pos: {{sun_sensor_roll_pos}}
sun_sensor_roll_neg: {{sun_sensor_roll_neg}}
time_stamp: {{time_stamp}}

----

=== Satellite AODS Sensor Data Specification
|===
|Field |Type |Item Type |Description |Source


|imu_gyro_x
|float

|

|The angular rate of the body with to respective to the x-axis in the IMU's reference frame.

|



|imu_gyro_y
|float

|

|The angular rate of the body with to respective to the y-axis in the IMU's reference frame.

|



|imu_gyro_z
|float

|

|The angular rate of the body with to respective to the z-axis in the IMU's reference frame.

|



|imu_magnetometer_x
|float

|

|The magnetic field strength with respective to the x-axis in the IMU's reference frame.

|



|imu_magnetometer_y
|float

|

|The magnetic field strength with respective to the y-axis in the IMU's reference frame.

|



|imu_magnetometer_z
|float

|

|The magnetic field strength with respective to the z-axis in the IMU's reference frame.

|



|sun_sensor_pitch_pos
|float

|

|Sun sensor measurement with respect to positive pitch angle.

a|
* []




|sun_sensor_pitch_neg
|float

|

|Sun sensor measurement with respect to negative pitch angle.

a|
* []




|sun_sensor_yaw_pos
|float

|

|Sun sensor measurement with respect to positive yaw angle.

a|
* []




|sun_sensor_yaw_neg
|float

|

|Sun sensor measurement with respect to negative yaw angle.

a|
* []




|sun_sensor_roll_pos
|float

|

|Sun sensor measurement with respect to positive roll angle.

a|
* []




|sun_sensor_roll_neg
|float

|

|Sun sensor measurement with respect to negative roll angle.

a|
* []




|time_stamp
|string

|

|Time stamp of the last transmission.

|



|===


==== *Derived From:*




* xref:{doc-name}#_4_2_request_satellite_aods_sensor_data[Request Satellite AODS Sensor Data]





=== TLE
*Purpose:* Data structure for the TLE data

=== TLE Template
----
tle_line_1: {{tle_line_1}}
tle_line_2: {{tle_line_2}}

----

=== TLE Specification
|===
|Field |Type |Item Type |Description |Source


|tle_line_1
|3-DataStructures/5-TLELine1.yaml

|

|Data for TLE line 1

|



|tle_line_2
|3-DataStructures/6-TLELine2.yaml

|

|Data for TLE line 2

|



|===


==== *Derived From:*



* https://www.celestrak.com/NORAD/documentation/tle-fmt.php[Two-Line Element Data]






=== TLE Line 1
*Purpose:* Data structure for the first line of the TLE data

=== TLE Line 1 Template
----
line_number: {{line_number}}
satellite_number: {{satellite_number}}
classification: {{classification}}
international_designator_1: {{international_designator_1}}
international_designator_2: {{international_designator_2}}
international_designator_3: {{international_designator_3}}
epoch_year: {{epoch_year}}
epoch: {{epoch}}
first_dt: {{first_dt}}
second_dt: {{second_dt}}
bstar: {{bstar}}
eph_type: {{eph_type}}
element_number: {{element_number}}
checksum: {{checksum}}

----

=== TLE Line 1 Specification
|===
|Field |Type |Item Type |Description |Source


|line_number
|string

|

|Line number of element data (Column 01)

|



|satellite_number
|string

|

|Satellite number (Column 03-07)

|



|classification
|string

|

|Classification of satellite (Column 08)

|



|international_designator_1
|string

|

|International designator 1 (last two digits of launch year) (Column 10-11)

|



|international_designator_2
|string

|

|International designator 2 (launch number of the year) (Column 12-14)

|



|international_designator_3
|string

|

|International designator 3 (piece of the launch) (Column 15-17)

|



|epoch_year
|string

|

|Epoch year (last two digits of year) (Column 19-20)

|



|epoch
|string

|

|Epoch (day of the year and fractional portion of the day) (Column 21-32)

|



|first_dt
|string

|

|First time derivative of the mean motion (Column 34-43)

|



|second_dt
|string

|

|Second time derivative of the mean motion (leading decimal point assumed) (Column 45-52)

|



|bstar
|string

|

|BSTAR drag term (leading decimal point assumed) (Column 54-61)

|



|eph_type
|string

|

|Ephemeris type (Column 63)

|



|element_number
|string

|

|Element number (Column 65-68)

|



|checksum
|string

|

|Checksum (modulo 10) (letters, blanks, periods, plus signs = 0; minus signs = 1) (Column 69)

|



|===


==== *Derived From:*



* https://www.celestrak.com/NORAD/documentation/tle-fmt.php[Two-Line Element Data]






=== TLE Line 2
*Purpose:* Data structure for the second line of the TLE data

=== TLE Line 2 Template
----
line_number: {{line_number}}
satellite_number: {{satellite_number}}
inclination: {{inclination}}
raan: {{raan}}
ecc: {{ecc}}
perigee: {{perigee}}
mean_anomaly: {{mean_anomaly}}
mean_motion: {{mean_motion}}
rev_epoch: {{rev_epoch}}
checksum: {{checksum}}

----

=== TLE Line 2 Specification
|===
|Field |Type |Item Type |Description |Source


|line_number
|string

|

|Line number of element data (Column 01)

|



|satellite_number
|string

|

|Satellite number (Column 03-07)

|



|inclination
|string

|

|Inclination (degrees) (Column 09-16)

|



|raan
|string

|

|Right ascension of the ascending node (degrees) (Column 18-25)

|



|ecc
|string

|

|Eccentricity (leading decimal point assumed) (Column 27-33)

|



|perigee
|string

|

|Argument of perigee (degrees) (Column 35-42)

|



|mean_anomaly
|string

|

|Mean anomaly (degrees) (Column 44-51)

|



|mean_motion
|string

|

|Mean motion (revs per day) (Column 53-63)

|



|rev_epoch
|string

|

|Revolution number at epoch (revs) (Column 64-68)

|



|checksum
|string

|

|Checksum (modulo 10) (letters, blanks, periods, plus signs = 0; minus signs = 1) (Column 69)

|



|===


==== *Derived From:*



* https://www.celestrak.com/NORAD/documentation/tle-fmt.php[Two-Line Element Data]







== Finite State Machine

[plantuml, fsm, svg]
....
include::./operating-mode-as-fsm.puml[Finite State Machine]
....
